class Config:
    def __init__(
        self,
        dataset='folder',
        dataroot='',
        workers=2,
        batchSize=64,
        imageSize=128,
        nz = 100,
        ndf = 64,
        ngf = 64,
        nc = 3,
        niter = 1000,
        lr = 0.0002,
        beta1 = 0.5,
        cuda = True,
        ngpu = 1,
        netG = '',
        netD = '',
        outf = '.',
        manualSeed = 42,
        nBottleneck = 4000,
        overlapPred = 4,
        nef = 64,
        wtl2 = 0.998,
        wtlD = 0.001,
        outpath: str = '',
      ):

      self.dataset=dataset,
      self.dataroot=dataroot,
      self.workers=workers,
      self.batchSize=batchSize,
      self.imageSize=imageSize,
      self.nz = nz,
      self.ndf = ndf,
      self.ngf = ngf,
      self.nc = nc,
      self.niter = niter,
      self.lr = lr,
      self.beta1 = beta1,
      self.cuda = cuda,
      self.ngpu = ngpu,
      self.netG = netG,
      self.netD = netD,
      self.outf = outf,
      self.manualSeed = manualSeed,
      self.nBottleneck = nBottleneck,
      self.overlapPred = overlapPred,
      self.nef = nef,
      self.wtl2 = wtl2,
      self.wtlD = wtlD,
      self.outpath: str = outpath
